#### Rebuilding the Basis single Layer Nuron from file name--> PyTorch Training Pipeline.ipynb with NN Module
#### V1

In [31]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [32]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [33]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0])

X_train.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
161,19.19,15.94,126.30,1157.0,0.08694,0.11850,0.11930,0.09667,0.1741,0.05176,...,22.03,17.81,146.60,1495.0,0.1124,0.2016,0.2264,0.17770,0.2443,0.06251
490,12.25,22.44,78.18,466.5,0.08192,0.05200,0.01714,0.01261,0.1544,0.05976,...,14.17,31.99,92.74,622.9,0.1256,0.1804,0.1230,0.06335,0.3100,0.08203
249,11.52,14.93,73.87,406.3,0.10130,0.07808,0.04328,0.02929,0.1883,0.06168,...,12.65,21.19,80.88,491.8,0.1389,0.1582,0.1804,0.09608,0.2664,0.07809
74,12.31,16.52,79.19,470.9,0.09172,0.06829,0.03372,0.02272,0.1720,0.05914,...,14.11,23.21,89.71,611.1,0.1176,0.1843,0.1703,0.08660,0.2618,0.07609
162,19.59,18.15,130.70,1214.0,0.11200,0.16660,0.25080,0.12860,0.2027,0.06082,...,26.73,26.39,174.90,2232.0,0.1438,0.3846,0.6810,0.22470,0.3643,0.09223

In [34]:
# SCALLLING
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



# LABELING
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

y_test

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0])

In [35]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [36]:
bias = torch.rand(1, dtype=torch.float64, requires_grad= True)

# V1

In [37]:
class model_V1(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)

        return out

    def loss_fun (self, y_preed, y):
        epsilon = 1e-7
        y_preed = torch.clamp(y_preed, epsilon, 1-epsilon)

        loss = -(y*torch.log(y_preed) + (1 - y)*torch.log(1-y_preed)).mean()
        return loss

In [38]:
learning_rate = 0.1
epochs = 45

learning_rate = 0.1
epochs = 45

In [41]:
print("X_train_tensor:", X_train_tensor.dtype)
print("y_train_tensor:", y_train_tensor.dtype)
print("Model weights:", model.linear.weight.dtype)

X_train_tensor: torch.float64
y_train_tensor: torch.int64
Model weights: torch.float32

In [42]:
X_train_tensor = X_train_tensor.to(torch.float32)

In [45]:
X_train_tensor.shape[1]

30

In [43]:
model = model_V1(X_train_tensor.shape[1])

for epoch in range(epochs):
    # forward Pass
    y_pred = model(X_train_tensor)


    # loss calculate
    loss = model.loss_fun(y_pred, y_train_tensor)
    print (f"{epoch} and loss {loss.item()}")

    # Backward pass
    loss.backward()
    
    # parametes Update
    with torch.no_grad():
        model.linear.weight -= learning_rate * model.linear.weight.grad       # we are doing GRADINT DECENT ---> Wnew = Wold - learingrate(dL/dW)
        model.linear.bias -= learning_rate * model.linear.bias.grad
    
    # Zero Grads
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()

0 and loss 0.7220834493637085
1 and loss 0.7130895853042603
2 and loss 0.7074045538902283
3 and loss 0.7035057544708252
4 and loss 0.7005603313446045
5 and loss 0.6981367468833923
6 and loss 0.6960184574127197
7 and loss 0.6940972208976746
8 and loss 0.6923187971115112
9 and loss 0.690654456615448
10 and loss 0.6890883445739746
11 and loss 0.6876102685928345
12 and loss 0.6862130761146545
13 and loss 0.6848913431167603
14 and loss 0.6836404800415039
15 and loss 0.6824561357498169
16 and loss 0.6813345551490784
17 and loss 0.6802722811698914
18 and loss 0.6792659759521484
19 and loss 0.6783125996589661
20 and loss 0.6774091124534607
21 and loss 0.6765528321266174
22 and loss 0.6757412552833557
23 and loss 0.6749719381332397
24 and loss 0.6742424964904785
25 and loss 0.6735507845878601
26 and loss 0.6728948354721069
27 and loss 0.6722726225852966
28 and loss 0.6716823577880859
29 and loss 0.6711224317550659
30 and loss 0.6705909967422485
31 and loss 0.6700867414474487
32 and loss 0.6696080565452576
33 and loss 0.6691537499427795
34 and loss 0.6687222719192505
35 and loss 0.668312668800354
36 and loss 0.667923629283905
37 and loss 0.6675541996955872
38 and loss 0.6672031879425049
39 and loss 0.6668696999549866
40 and loss 0.6665529012680054
41 and loss 0.6662517786026001
42 and loss 0.6659655570983887
43 and loss 0.665693461894989
44 and loss 0.6654348969459534

In [44]:
model.linear.weight

Parameter containing:
tensor([[ 0.0961, -0.1222,  0.1088, -0.0040,  0.0359, -0.0928, -0.0525, -0.1033,
          0.0336,  0.0409, -0.1416, -0.0148,  0.1272,  0.0738,  0.0611,  0.0749,
          0.0528, -0.0094,  0.0258, -0.1290, -0.1475,  0.1204,  0.0810, -0.0173,
         -0.0843,  0.0026, -0.0445,  0.0284,  0.0451,  0.0864]],
       requires_grad=True)

# as 30 input Features, so we have 30 Weights

In [ ]:
#