In [108]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [109]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [110]:
df.shape

(569, 33)

In [111]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
df.shape

(569, 31)

##### Train Test Split

In [112]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0])

X_train.head()

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
213,17.42,25.56,114.50,948.0,0.10060,0.11460,0.16820,0.06597,0.1308,0.05866,...,18.07,28.07,120.40,1021.0,0.1243,0.1793,0.2803,0.10990,0.1603,0.06818
486,14.64,16.85,94.21,666.0,0.08641,0.06698,0.05192,0.02791,0.1409,0.05355,...,16.46,25.44,106.00,831.0,0.1142,0.2070,0.2437,0.07828,0.2455,0.06596
160,11.75,20.18,76.10,419.8,0.10890,0.11410,0.06843,0.03738,0.1993,0.06453,...,13.32,26.21,88.91,543.9,0.1358,0.1892,0.1956,0.07909,0.3168,0.07987
288,11.26,19.96,73.72,394.1,0.08020,0.11810,0.09274,0.05588,0.2595,0.06233,...,11.86,22.33,78.27,437.6,0.1028,0.1843,0.1546,0.09314,0.2955,0.07009
475,12.83,15.73,82.89,506.9,0.09040,0.08269,0.05835,0.03078,0.1705,0.05913,...,14.09,19.35,93.22,605.8,0.1326,0.2610,0.3476,0.09783,0.3006,0.07802

In [113]:
y_train.head()

213    M
486    B
160    B
288    B
475    B
Name: diagnosis, dtype: object

#### Scaling

In [114]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [115]:
X_train, X_test

(array([[ 0.92987502,  1.39895279,  0.92054552, ..., -0.07736411,
         -2.05297887, -0.84690765],
        [ 0.14456388, -0.59225433,  0.09073489, ..., -0.55672571,
         -0.72770935, -0.96800878],
        [-0.67182072,  0.16902233, -0.64991915, ..., -0.54444605,
          0.38134836, -0.20921742],
        ...,
        [-1.10967406, -0.44822902, -1.10183672, ..., -1.20209014,
         -0.08529584, -0.30631653],
        [ 1.7547342 ,  0.47307577,  1.79575239, ...,  2.32702393,
          4.09894713,  1.01979549],
        [-1.02210339,  0.17130845, -0.95501463, ..., -0.81323419,
         -0.83970396,  0.35755773]]),
 array([[ 0.43269962,  0.85942939,  0.74468619, ...,  1.98895423,
          0.55089575,  0.99252046],
        [-1.1209735 ,  0.03414148, -1.11492393, ..., -1.40508355,
         -1.02791712, -0.88836569],
        [ 1.7406099 , -1.16606947,  1.76303438, ...,  0.72005588,
         -0.86925809, -0.37777711],
        ...,
        [-0.38650984, -1.38782273, -0.39676352, ..., -0.46834247,
         -0.55816196, -0.06411425],
        [-0.24244197, -1.07005259, -0.2965646 , ..., -0.22593285,
         -1.39345508, -1.18075403],
        [-1.33425045,  0.51651198, -1.32472819, ..., -1.17192159,
         -0.07907392, -0.03629372]]))

#### Lablel Encoder

In [116]:
label = LabelEncoder()
y_train = label.fit_transform(y_train)
y_test = label.transform(y_test)

y_test

array([1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

#### Numpy array to Torch

In [117]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [118]:
bias = torch.rand(1, dtype=torch.float64, requires_grad= True)
bias

tensor([0.5628], dtype=torch.float64, requires_grad=True)

#### Defing Model

In [119]:
class simpleNN():

    #Dfining the weights and Bias
    def __init__(self, x):
        self.weight = torch.rand(x.shape[1], 1, dtype= torch.float64, requires_grad= True )
        self.bias = torch.rand(1, dtype=torch.float64, requires_grad= True)

    # Making the FORWARD Relationships
    def forward(self, x):
        z = torch.matmul(x, self.weight) + self.bias
        y_preds = torch.sigmoid(z)
        return y_preds
    
    # Making the LOSS Functions
    def loss_fun (self, y_preed, y):
        epsilon = 1e-7
        y_preed = torch.clamp(y_preed, epsilon, 1-epsilon)

        loss = -(y*torch.log(y_preed) + (1 - y)*torch.log(1-y_preed)).mean()
        return loss

In [120]:
learning_rate = 0.1
epochs = 45

#### Training Pipeline

In [121]:
model = simpleNN(X_train_tensor)

for epoch in range(epochs):
    # forward Pass
    y_pred = model.forward(X_train_tensor)


    # loss calculate
    loss = model.loss_fun(y_pred, y_train_tensor)
    print (f"{epoch} and loss {loss.item()}")

    # Backward pass
    loss.backward()
    
    # parametes Update
    with torch.no_grad():
        model.weight -= learning_rate * model.weight.grad       # we are doing GRADINT DECENT ---> Wnew = Wold - learingrate(dL/dW)
        model.bias -= learning_rate * model.bias.grad
    
    # Zero Grads
    model.weight.grad.zero_()
    model.bias.grad.zero_()

0 and loss 3.810308789683934
1 and loss 3.688128132018232
2 and loss 3.5632932185062085
3 and loss 3.429761326118125
4 and loss 3.2852167396146688
5 and loss 3.1358097092183086
6 and loss 2.985723954495479
7 and loss 2.831190083959924
8 and loss 2.674697611875855
9 and loss 2.5190383270125594
10 and loss 2.3599692619604555
11 and loss 2.1982417736488187
12 and loss 2.03338255873629
13 and loss 1.86580789041224
14 and loss 1.707929744612956
15 and loss 1.5617284426792923
16 and loss 1.4279991646460863
17 and loss 1.3069139577458058
18 and loss 1.2032385896533189
19 and loss 1.1174782094188904
20 and loss 1.049152709277394
21 and loss 0.9968758609891792
22 and loss 0.9583438484090195
23 and loss 0.9304482262704414
24 and loss 0.9099717390706997
25 and loss 0.8943451437569415
26 and loss 0.8818251399696605
27 and loss 0.8713111463763994
28 and loss 0.8621269766383756
29 and loss 0.8538611759202757
30 and loss 0.8462636158274365
31 and loss 0.8391812708825951
32 and loss 0.8325191075541272
33 and loss 0.8262165483988338
34 and loss 0.8202334278129951
35 and loss 0.8145416672699514
36 and loss 0.8091203692901394
37 and loss 0.8039529418480508
38 and loss 0.7990254219039357
39 and loss 0.7943255032484926
40 and loss 0.789841975671463
41 and loss 0.7855644028334612
42 and loss 0.7814829376633098
43 and loss 0.7775882163140329
44 and loss 0.7738712965341614

In [122]:
model.bias

tensor([-0.0769], dtype=torch.float64, requires_grad=True)

In [123]:
# Model Evaluation
with torch.no_grad():                     # Disable gradient calculation

    y_pred = model.forward(X_test_tensor) # Predict probabilities

    y_pred = (y_pred > 0.5).float()       # Convert probabilities to 0 or 1

    accuracy = (y_pred == y_test_tensor).float().mean()  # Calculate accuracy

    print(f"Accuracy: {accuracy.item()}") # Print accuracy

Accuracy: 0.5187050700187683